# -*- coding: utf-8 -*-
"""Projeto 02 - Case Educação.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1okv2m5w2d25ua8RvxaqVMydpnH4lKqqG
"""

#Importando as bibliotecas:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

#Lendo o arquivo/base de dados que será tratada:

Base_Dados = pd.read_csv('StudentsPerformance+(1).csv')

#Verificando a dimensão da data base:
Base_Dados.shape

#Verificando campos nulos:
Nulos = Base_Dados.isnull()

plt.figure(figsize=(16,5))
plt.title('Analisando campos nulos:')
sns.heatmap(Nulos, cbar = False);

#Verificando campos únicos/unique:
Base_Dados.nunique()

#Verificando se há alguma informação duplicada:
Base_Dados.duplicated()

#Estatística:
Base_Dados.describe()

#INFO:
Base_Dados.info()

#Verificando informações da coluna selecionada em porcentagem (%) :
Base_Dados['gender'].value_counts(normalize=True) * 100

Base_Dados['race/ethnicity'].value_counts(normalize=True) * 100

Base_Dados['parental level of education'].value_counts(normalize=True) * 100



#Verificando em boxplot a relação entre notas de matemática do gênero masculino x feminino:
sns.boxplot(data=Base_Dados, x = 'math score', y='gender')

#Verificando a relação das mesmas entre notas de leitura/reading score.
sns.boxplot(data=Base_Dados, x='reading score', y='gender')

#Verificando a relação dos mesmos na nota de redação:
sns.boxplot(data=Base_Dados,x='writing score', y='gender')

#Criar um pairplot ( grid com vários gráficos ):
sns.pairplot(Base_Dados)

sns.pairplot(Base_Dados, hue = 'race/ethnicity')

sns.boxplot(data=Base_Dados, x='math score', y='race/ethnicity')

